GET http://127.0.0.1:8001/user/get/1

###

POST http://127.0.0.1:8001/user/create
Content-Type: application/json

{
  "name":"xuexuan"
}

###

GET http://localhost:80/consumer/user/create?name=xuexuan


###

GET http://localhost:80/consumer/user/get/1

###

GET http://127.0.0.1:8001/user/user/discovery

###

GET http://127.0.0.1:8004/user/zk

###

GET http://127.0.0.1:80/consumer/user/zk

###
GET http://localhost:8080/user/consul

###
GET http://127.0.0.1:80/consumer/user/consul

###
GET http://localhost/consumer/user/get/1

###
GET http://127.0.0.1:8007/user/ok/1


###
GET http://127.0.0.1:8007/user/timeout/1

###
GET http://127.0.0.1:80/user/ok/1

###
GET http://127.0.0.1:80/user/timeout/1

###
GET http://127.0.0.1:8429/user/get/1

###
GET http://localhost:8429/user/listAll

###
GET http://localhost:3456/main/config-dev.yml

###
GET http://localhost:4567/fetchConfig

###
GET http://localhost:4568/fetchConfig

### 刷新配置
POST http://localhost:4567/actuator/refresh

###
POST http://localhost:4568/actuator/refresh

### 配置中心更新配置 通知其他服务
POST http://localhost:3456/actuator/busrefresh

### 通知指定实例 https://docs.spring.io/spring-cloud-bus/docs/current/reference/html/#addressing-an-instance
### configclient4567后面的为bus.id
POST http://localhost:3456/actuator/busrefresh/configclient4567


### nacos
GET http://localhost:9001/user/get

###
GET http://localhost:80/user/get

###
GET http://localhost:80/user/get2

###
GET http://localhost:3377/configInfo

###
GET http://127.0.0.1:8401/byResource
