GET http://127.0.0.1:8001/user/get/1

###

POST http://127.0.0.1:8001/user/create
Content-Type: application/json

{
  "name":"xuexuan"
}

###

GET http://localhost:80/consumer/user/create?name=xuexuan


###

GET http://localhost:80/consumer/user/get/1

###

GET http://127.0.0.1:8001/user/user/discovery

###

GET http://127.0.0.1:8004/user/zk

###

GET http://127.0.0.1:80/consumer/user/zk

###
GET http://localhost:8080/user/consul

###
GET http://127.0.0.1:80/consumer/user/consul

###
GET http://localhost/consumer/user/get/1

###
GET http://127.0.0.1:8007/user/ok/1


###
GET http://127.0.0.1:8007/user/timeout/1

###
GET http://127.0.0.1:80/user/ok/1

###
GET http://127.0.0.1:80/user/timeout/1

###
GET http://127.0.0.1:8429/user/get/1
