GET http://127.0.0.1:8001/user/get/1

###

POST http://127.0.0.1:8001/user/create
Content-Type: application/json

{
  "name":"xuexuan"
}

###

GET http://localhost:80/consumer/user/create?name=xuexuan


###

GET http://localhost:80/consumer/user/get/1




