server:
  port: 80
spring:
  application:
    name: nacos-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-provider: http://nacos-user-provider