server:
  port: 80
spring:
  application:
    name: user-consumer
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 1000
            connectTimeout: 1000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    instance-id: user-consumer
    prefer-ip-address: true