server:
  port: 8002
spring:
  application:
    name: user-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    instance-id: provider-8002
    prefer-ip-address: true